# Generated by Django 4.2 on 2023-12-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootCamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('teachers', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Django',
        ),
        migrations.DeleteModel(
            name='ProductDesign',
        ),
        migrations.DeleteModel(
            name='ProductManagement',
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
